### ISSUE TITLE
travis2docker runs: postgresql is not found

### ISSUE THREAD

**Issue by gurneyalex** [OCA/runbot-addons#176]
I see a lot of builds not available to interact with. In the job_30_xxx.txt logs of these we get

```
======== Testing test_server.py ========
command:  /entrypoint_image
 * Starting PostgreSQL 9.6 database server                                       * Removed stale pid file.
The PostgreSQL server failed to start. Please check the log output:
2018-09-04 11:24:13 UTC [125]: [1-1] db=,user=FATAL:  lock file "/var/run/postgresql/.s.PGSQL.5432.lock" already exists
2018-09-04 11:24:13 UTC [125]: [2-1] db=,user=HINT:  Is another postmaster (PID 103) using socket file "/var/run/postgresql/.s.PGSQL.5432"?
2018-09-04 11:24:13 UTC [125]: [3-1] db=,user=LOG:  database system is shut down
                                                                         [fail]
Waiting to start psql service...
Traceback (most recent call last):
  File "/entrypoint_image", line 120, in <module>
    docker_entrypoint()
  File "/entrypoint_image", line 98, in docker_entrypoint
    raise RuntimeError("PSQL not started.")
RuntimeError: PSQL not started.
Working in /home/odoo/build/OCA/account-invoicing
Using repo OCA/OCB and addons path /home/odoo/build/OCA/account-invoicing,/home/odoo/OCB-11.0/addons
Modules to test: ['account_invoice_check_total', 'account_invoice_force_number', 'account_invoice_line_description', 'account_invoice_refund_link', 'account_invoice_reimbursable', 'account_invoice_supplier_ref_reuse', 'account_invoice_supplier_ref_unique', 'account_invoice_supplier_self_invoice', 'account_invoice_tax_required', 'account_invoice_triple_discount', 'account_invoice_view_payment', 'account_payment_term_extension', 'sale_timesheet_invoice_description']
Modules to preinstall: ['account', 'decimal_precision', 'sales_team', 'account_invoicing', 'project', 'sale_management', 'base_setup', 'web_planner', 'sale_timesheet', 'web_tour', 'base', 'sale', 'http_routing', 'resource', 'web', 'product', 'bus', 'mail', 'analytic', 'portal', 'hr', 'hr_timesheet']

Creating instance:
createdb: could not connect to database template1: could not connect to server: Connection refused
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
Using previous openerp_template database.

Testing ['account_invoice_check_total', 'account_invoice_force_number', 'account_invoice_line_description', 'account_invoice_refund_link', 'account_invoice_reimbursable', 'account_invoice_supplier_ref_reuse', 'account_invoice_supplier_ref_unique', 'account_invoice_supplier_self_invoice', 'account_invoice_tax_required', 'account_invoice_triple_discount', 'account_invoice_view_payment', 'account_payment_term_extension', 'sale_timesheet_invoice_description']:
createdb: could not connect to database template1: could not connect to server: Connection refused
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
/home/odoo/OCB-11.0/odoo-bin -d openerp_test --db-filter=^openerp_test$ --log-level info --pidfile=/tmp/odoo.pid
2018-09-04 11:36:32,139 2080 INFO ? odoo: Odoo version 11.0
2018-09-04 11:36:32,139 2080 INFO ? odoo: Using configuration file at /home/odoo/.openerp_serverrc
2018-09-04 11:36:32,139 2080 INFO ? odoo: addons paths: ['/home/odoo/data_dir/addons/11.0', '/home/odoo/build/OCA/account-invoicing', '/home/odoo/OCB-11.0/addons', '/.repo_requirements/odoo/odoo/addons']
2018-09-04 11:36:32,140 2080 INFO ? odoo: database: default@default:default
2018-09-04 11:36:32,140 2080 INFO ? odoo.sql_db: Connection to the database failed
Traceback (most recent call last):
File "/home/odoo/OCB-11.0/odoo-bin", line 8, in <module>
odoo.cli.main()
File "/.repo_requirements/odoo/odoo/cli/command.py", line 60, in main
o.run(args)
File "/.repo_requirements/odoo/odoo/cli/server.py", line 175, in run
main(args)
File "/.repo_requirements/odoo/odoo/cli/server.py", line 140, in main
odoo.service.db._create_empty_database(db_name)
File "/.repo_requirements/odoo/odoo/service/db.py", line 95, in _create_empty_database
with closing(db.cursor()) as cr:
File "/.repo_requirements/odoo/odoo/sql_db.py", line 634, in cursor
return Cursor(self.__pool, self.dbname, self.dsn, serialized=serialized)
File "/.repo_requirements/odoo/odoo/sql_db.py", line 178, in __init__
self._cnx = pool.borrow(dsn)
File "/.repo_requirements/odoo/odoo/sql_db.py", line 517, in _locked
return fun(self, *args, **kwargs)
File "/.repo_requirements/odoo/odoo/sql_db.py", line 585, in borrow
**connection_info)
File "/.repo_requirements/virtualenv/python3.5/lib/python3.5/site-packages/psycopg2/__init__.py", line 130, in connect
conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: Connection refused
Is the server running locally and accepting
connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?

----------
Modules loaded message not found.
----------
FAIL Command exited with code 1
FAIL Found 1 lines with errors
Module test summary
FAIL account_invoice_check_total,account_invoice_force_number,account_invoice_line_description,account_invoice_refund_link,account_invoice_reimbursable,account_invoice_supplier_ref_reuse,account_invoice_supplier_ref_unique,account_invoice_supplier_self_invoice,account_invoice_tax_required,account_invoice_triple_discount,account_invoice_view_payment,account_payment_term_extension,sale_timesheet_invoice_description

+=======================================
|  Tests summary:
|---------------------------------------
| test_server.py              FAIL
+=======================================

```

@moylop260  do you have any idea how I can check what is going on?

**Comment by moylop260** [comment]
Hi @gurneyalex 
Could you share me the last changes to this server?

It seems a configuration with the FS since that I can't reproduce it.

Could you share the repositories and shas used in production, please?

**Comment by moylop260** [comment]
@luisg123v 
Could you check it, please?
Maybe deleting the `lock file "/var/run/postgresql/.s.PGSQL.5432.lock" already exists` manually from runbot when it is started.

**Comment by gurneyalex** [comment]
@moylop260 sure

Odoo version: https://github.com/OCA/OCB/commit/b3a4bfd815bdb854fe4568a8eb5c94e544aebe09
odoo-extra: https://github.com/gurneyalex/odoo-extra/commit/45ce02d413a082f4f9d7dabe3c65513a0a3265ee
runbot-addons: https://github.com/gurneyalex/runbot-addons/commit/52888d5227a0e082fa70ba921e8a432e6e3b0842

and travis2docker==4.0.6

docker --version: Docker version 17.05.0-ce, build 89658be

```
$ docker info
Containers: 165
 Running: 165
 Paused: 0
 Stopped: 0
Images: 3493
Server Version: 17.05.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 35688
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.0-7-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 12
Total Memory: 125.9GiB
Name: runbot1
ID: WRV3:RCFA:HGBF:45H6:J4LD:LWW2:4R4W:HILR:QAIZ:YL2F:MU6C:FJ5O
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by gurneyalex** [comment]
There are other instances in which the docker container is up, but postgresql is not running inside the container. Example http://3337200-8-0-233bbf.runbot2.odoo-community.org/?db=3337200-8-0-233bbf-all

**Comment by gurneyalex** [comment]
@moylop260 I proposed a fix in https://github.com/Vauxoo/travis2docker/pull/119

Testing on the odoo-community runbot apparently with success.

**Comment by moylop260** [comment]
Please, check the following changes:
 - https://github.com/OCA/runbot-addons/pull/179
 - https://github.com/Vauxoo/travis2docker/pull/120
