### ISSUE TITLE
ResourceNotFound Error with runbot_gitlab

### ISSUE THREAD

**Issue by npiganeau** [OCA/runbot-addons#61]
Hi,

I use gitlab 7.14.1 (docker image) with runbot (Odoo v8 + runbot master from odoo-extra).

The runbot works perfectly for building branches from gitlab without gitlab integration with runbot_gitlab module.

However, when I install runbot_gitlab and set "use gitlab" option I get the following error:

```
runbot_1 | 2015-08-31 17:21:23,393 53 ERROR runbot openerp.http: Exception during JSON request handling.
runbot_1 | Traceback (most recent call last):
runbot_1 |   File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 530, in _handle_exception
runbot_1 |     return super(JsonRequest, self)._handle_exception(exception)
runbot_1 |   File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 567, in dispatch
runbot_1 |     result = self._call_function(**self.params)
runbot_1 |   File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 303, in _call_function
runbot_1 |     return checked_call(self.db, *args, **kwargs)
runbot_1 |   File "/usr/lib/python2.7/dist-packages/openerp/service/model.py", line 113, in wrapper
runbot_1 |     return f(dbname, *args, **kwargs)
runbot_1 |   File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 300, in checked_call
runbot_1 |     return self.endpoint(*a, **kw)
runbot_1 |   File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 796, in __call__
runbot_1 |     return self.method(*args, **kw)
runbot_1 |   File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 396, in response_wrap
runbot_1 |     response = f(*args, **kw)
runbot_1 |   File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 953, in call_button
runbot_1 |     action = self._call_kw(model, method, args, {})
runbot_1 |   File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 941, in _call_kw
runbot_1 |     return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
runbot_1 |   File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 241, in wrapper
runbot_1 |     return old_api(self, *args, **kwargs)
runbot_1 |   File "/opt/runbot-addons/runbot/runbot.py", line 403, in cron
runbot_1 |     self.update(cr, uid, ids, context=context)
runbot_1 |   File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 241, in wrapper
runbot_1 |     return old_api(self, *args, **kwargs)
runbot_1 |   File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 393, in old_api
runbot_1 |     result = new_api(recs, *args, **kwargs)
runbot_1 |   File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 397, in new_api
runbot_1 |     result = [method(rec, *args, **kwargs) for rec in self]
runbot_1 |   File "/opt/runbot-addons/runbot_gitlab/runbot_repo.py", line 81, in gitlab_func
runbot_1 |     return func(self, *args, **kwargs)
runbot_1 |   File "/opt/runbot-addons/runbot_gitlab/runbot_repo.py", line 207, in update
runbot_1 |     source_branch = source_project.branch(name=mr.source_branch)
runbot_1 |   File "/usr/lib/python2.7/dist-packages/gitlab3/__init__.py", line 155, in fn
runbot_1 |     data = parent._get(fixed_url, addl_keys=key, data=kwargs)
runbot_1 |   File "/usr/lib/python2.7/dist-packages/gitlab3/__init__.py", line 415, in _get
runbot_1 |     return self._request(requests.get, api_url, addl_keys, data)
runbot_1 |   File "/usr/lib/python2.7/dist-packages/gitlab3/__init__.py", line 435, in _request
runbot_1 |     self._check_status_code(r.status_code, url, data)
runbot_1 |   File "/usr/lib/python2.7/dist-packages/gitlab3/__init__.py", line 411, in _check_status_code
runbot_1 |     raise self._code_to_exc[status_code](msg)
runbot_1 | ResourceNotFound: URL: https://gitlab.ndp-systemes.fr/api/v3/projects/3/repository/branches/:branch, Data: {'name': u'thomas-entrepot'}
```

But when I call from a web browser the following url:

```
https://gitlab.ndp-systemes.fr/api/v3/projects/3/repository/branches/thomas-entrepot?private-token=XXXXXXX
```

I get a JSON response which describes the branch

Any idea of what I am missing ?

**Comment by npiganeau** [comment]
Found that we need to apply eb8b3150612e543a19fbb1acf3e398ff600abaa3 for the module to work correctly.

Also gitlab integration fails if the token has special characters (such as -). Actually GitLab user tokens are generated with special characters, but GitLab refuses to use such a token for gitlab-ci service.

**Comment by OSguard** [comment]
can we close this?

**Comment by hbrunn** [comment]
looks like
